apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-image-updater
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-image-updater
  template:
    metadata:
      labels:
        app: k8s-image-updater
    spec:
      serviceAccountName: k8s-image-updater
      containers:
      - name: k8s-image-updater
        image: k8s-image-updater:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: k8s-image-updater
              key: api-key
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-image-updater
  namespace: kube-system
spec:
  selector:
    app: k8s-image-updater
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 