apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-image-updater
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-image-updater
  template:
    metadata:
      labels:
        app: k8s-image-updater
    spec:
      serviceAccountName: k8s-image-updater
      containers:
      - name: k8s-image-updater
        image: ghcr.io/monlor/k8s-image-updater:main
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          value: "z0ooJ352l3sYLPo5KYo1224pf3GKF6MFM89ZRgHbKsGM8Gmg5WuBztArTL6pcbgG"
        - name: UPDATER_ENABLED
          value: "true"
        - name: IMAGE_UPDATE_INTERVAL
          value: "1m"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-image-updater
  namespace: kube-system
spec:
  selector:
    app: k8s-image-updater
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-updater
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-image-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-image-updater
subjects:
- kind: ServiceAccount
  name: k8s-image-updater
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-image-updater
  apiGroup: rbac.authorization.k8s.io 