apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-updater
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-image-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-image-updater
subjects:
- kind: ServiceAccount
  name: k8s-image-updater
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-image-updater
  apiGroup: rbac.authorization.k8s.io 