apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-latest
  namespace: default
  labels:
    image-updater.k8s.io/enabled: "true"
  annotations:
    image-updater.k8s.io/mode: "latest"
    image-updater.k8s.io/container: "nginx"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: p.gz.mk/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-name
  namespace: default
  labels:
    image-updater.k8s.io/enabled: "true"
  annotations:
    image-updater.k8s.io/mode: "name"
    image-updater.k8s.io/container: "nginx"
    image-updater.k8s.io/allow-tags: "regexp:^[0-9.]+-bookworm$"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: p.gz.mk/nginx:1.27.5-bookworm
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset-digest
  namespace: default
  labels:
    image-updater.k8s.io/enabled: "true"
  annotations:
    image-updater.k8s.io/mode: "digest"
spec:
  serviceName: nginx-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sts
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
      - name: nginx
        image: p.gz.mk/nginx:1.26.3-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset-release
  namespace: default
  labels:
    image-updater.k8s.io/enabled: "true"
  annotations:
    image-updater.k8s.io/mode: "release"
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx
        image: p.gz.mk/nginx:1.26.3-alpine3.20-perl
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 